image: ubuntu/lts
sources:
    - https://git.sr.ht/~tfardet/NNGT
secrets:
    - ceb490c3-68b4-41f7-9aa9-eb2e4b91d424
    - 0b249c79-8eaf-4b82-b1d1-f3c38c7eae4b
tasks:
    - check: |
        mv .coveralls.yml NNGT/.coveralls.yml || true
        cd NNGT
        python3 extra/check_headers.py
    - setup: |
        sudo apt install -y software-properties-common
        sudo sh -c 'echo -n "deb https://downloads.skewed.de/apt focal main\n" >> /etc/apt/sources.list'
        sudo apt-key adv --keyserver keys.openpgp.org --recv-key 612DEFB798507F25
        sudo add-apt-repository -y ppa:nest-simulator/nest
        sudo apt-get update -qq
        sudo apt install -y gcc libcairo2-dev pkg-config build-essential autoconf automake python3-dev libblas-dev
        sudo apt install -y nest liblapack-dev libatlas-base-dev gfortran libxml2-dev openmpi-bin libopenmpi-dev libgmp-dev
        sudo apt install -y python3-pip python3-tk libigraph0v5 libigraph0-dev python3-graph-tool
        pip3 install numpy scipy cython mpi4py
        pip3 install networkx python-igraph
        pip3 install pycairo matplotlib seaborn shapely svg.path dxfgrabber
        pip3 install pytest pytest-mpi cov-core coverage coveralls[yaml]
        cd NNGT
        python3 setup.py install --user
        echo 'export PATH=$PATH:/home/build/.local/bin' >> /home/build/.buildenv
    - test: |
        cd NNGT
        GL=all coverage run -p -m pytest testing/library_compatibility.py
        GL=gt coverage run -p -m pytest testing
        GL=nx coverage run -p -m pytest testing
        GL=ig coverage run -p -m pytest testing
        GL=nngt coverage run -p -m pytest testing
        GL=gt OMP=2 coverage run -p -m pytest testing
        GL=gt OMP=0 MPI=1 mpirun -n 2 coverage run -p -m pytest --with-mpi testing
        coverage combine
        GIT_BRANCH=$(git show -s --pretty=%D HEAD | tr -s ', /' '\n' | grep -v HEAD | sed -n 2p)
        CI_NAME=$BUILD_SUBMITTER CI_BUILD_NUMBER=$JOB_ID CI_BUILD_URL=$JOB_URL CI_BRANCH=$GIT_BRANCH coveralls
