# SPDX-FileCopyrightText: 2015-2023 Tanguy Fardet
# SPDX-License-Identifier: CC0-1.0

version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"

submodules:
  include: all

conda:
  environment: doc/environment.yml

python:
   install:
   - method: pip
     path: .

sphinx:
   configuration: doc/conf.py
