language: generic

#For Ubuntu Trusty (14.04 LTS)
sudo: required
dist: trusty

# add toolchains for newer, C++14 supporting gcc-6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6

env:
    - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

matrix:
    include:
        - python: "2.7"
          env: GL="gt" PYVERSION="2.7"
        - python: "2.7"
          env: GL="nngt" PYVERSION="2.7"
        - python: "2.7"
          env: GL="ig" PYVERSION="2.7"
        - python: "2.7"
          env: GL="nx" PYVERSION="2.7"
        - python: "3.5"
          env: GL="gt" PYVERSION="3.x"
        - python: "3.5"
          env: GL="ig" PYVERSION="3.5"
        - python: "3.5"
          env: GL="nx" PYVERSION="3.x"
        - python: "3.5"
          env: GL="nngt" PYVERSION="3.x"
    fast_finish: true

cache:
    - apt
    - pip

before_install:
    - if [[ "$GL" == "gt" ]]; then sudo sh -c 'echo -n "deb http://downloads.skewed.de/apt/trusty trusty universe\n" >> /etc/apt/sources.list'; fi
    - if [[ "$GL" == "gt" ]]; then sudo sh -c 'echo -n "deb-src http://downloads.skewed.de/apt/trusty trusty universe\n" >> /etc/apt/sources.list'; fi
    # update package repository status (-qq is more quiet)
    - sudo rm -rf /var/lib/apt/lists/*
    - ls /etc/apt/sources.list.d/
    - sudo apt-get --allow-unauthenticated update -qq
    # remove any obsolete libraries
    - sudo apt-get autoremove
    # requirements for building + installing scipy
    - sudo apt-get install -y build-essential autoconf automake libtool python-all-dev libblas-dev liblapack-dev libatlas-base-dev gfortran libxml2-dev openmpi-bin libopenmpi-dev
    # Geos for shapely
    - sudo apt-get install libgeos-3.4.2 libgeos-dev
    # install scipy from apt (much faster when possible) and pip if necessary
    - if [[ "$PYVERSION" == "2.7" ]]; then sudo apt-get install -y python-scipy python-gtk2-dev; fi
    - if [[ "$PYVERSION" == "3.x" ]]; then sudo apt-get install -y python3-scipy python3-pip; fi
    - if [[ "$PYVERSION" == "3.5" ]]; then sudo pip install scipy; fi
    # Pip alias and additional libraries
    - shopt -s expand_aliases
    - if [[ "$PYVERSION" == "3.x" ]]; then alias sudo='sudo -H ' && alias pipv=pip3; else alias sudo='sudo -H ' && alias pipv=pip; fi
    - sudo pipv install -U setuptools
    - sudo pipv install --user cython
    - sudo pipv install mpi4py shapely matplotlib numpy
    # install graph-tool, igraph, and networkx
    - if [[ "$PYVERSION" == "2.7" && "$GL" == "gt" ]]; then sudo apt-get --allow-unauthenticated install -y python-graph-tool; fi
    - if [[ "$PYVERSION" == "3.x" && "$GL" == "gt" ]]; then sudo apt-get --allow-unauthenticated install -y python3-graph-tool; fi
    - if [[ "$PYVERSION" == "3.x" && "$GL" == "ig" ]]; then sudo apt-get install python3-cairo libxml2-dev; fi
    - if [[ "$GL" == "ig" ]]; then sudo pipv install python-igraph; fi
    - if [[ "$GL" == "nx" ]]; then sudo pipv install networkx; fi
    # testing and coverage analysis
    - sudo pipv install nose2 cov-core coverage coveralls

install: sudo pipv install -e .

script:
    - coverage run -m nose2.__main__ -F
    - export OMP=4 && coverage run -m nose2.__main__ -F
    - export OMP=1 && export MPI=1 && mpirun -n 4 coverage run -m nose2.__main__ -F

after_success: coveralls
