# SPDX-FileCopyrightText: 2015-2023 Tanguy Fardet
# SPDX-License-Identifier: CC0-1.0

channels:
    - conda-forge
dependencies:
    - cython
    - python=3.8
    - numpy
    - scipy
    - pandas
    - matplotlib
    - cartopy
    - pip:
        - furo
        - peewee
        - sphinx-gallery
        - sphinx-copybutton
        - networkx>=2.4
        - shapely
        - dxfgrabber
        - geopandas
        - cartopy>=0.20
